require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Bundler/OrderedGems:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: percent_r
  AllowInnerSlashes: false

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics:
  Enabled: false

Layout/BeginEndAlignment:
  EnforcedStyleAlignWith: begin

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/YodaCondition:
  EnforcedStyle: forbid_for_equality_operators_only

Gemspec/RequireMFA:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false
